/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rubicon.menus;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import rubicon.Data;
import rubicon.Upgrade;

/**
 *
 * @author user
 */
public class UpgradePanel extends javax.swing.JPanel {

    
    Data data;
    ActionListener action;
    public UpgradePanel(String upName,String d, int level, int next, ActionListener a) {
        initComponents();
        upgradeName.setText(upName);
        description.setText(d);
        currentLevel.setText(level+"");
        nextLevel.setText(next+"");
        jButton1.addActionListener(a);
    }
    public UpgradePanel(String upName) {
        initComponents();
        description.setBackground(new Color(0, 0, 0, 0));
        upgradeName.setText(upName);
        jButton1.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent ae) {
                buy();
                action.actionPerformed(ae);
            }
            
        });
    }
    
    public void addListener(ActionListener a){
        action = a;
    }
    
    public void update(Data d){
        Upgrade u = d.getUpgrade(upgradeName.getText());
        data = d;
        description.setText(u.getDescription());
        currentLevel.setText(u.getCurrentLevel()+"");
        if(u.getUpgradeCost() < 0)
            nextLevel.setText("Max Level");
        else
            nextLevel.setText(u.getUpgradeCost()+"");
        
        if(u.getUpgradeCost() < 0 || d.getMoney() < u.getUpgradeCost())
            jButton1.setEnabled(false);
        else
            jButton1.setEnabled(true);
    }
    
    public void buy(){
        Upgrade u = data.getUpgrade(upgradeName.getText());
        data.setMoney(data.getMoney()-u.getUpgradeCost());
        u.levelUp();
        currentLevel.setText(u.getCurrentLevel()+"");
        if(u.getUpgradeCost() < 0){
            nextLevel.setText("Max Level");
            jButton1.setEnabled(false);
        }
        else
            nextLevel.setText(u.getUpgradeCost()+"");
    }
    
    public void update(){
        Upgrade u = data.getUpgrade(upgradeName.getText());
        if(u.getUpgradeCost() < 0 || data.getMoney() < u.getUpgradeCost())
            jButton1.setEnabled(false);
        else
            jButton1.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upgradeName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        currentLevel = new javax.swing.JLabel();
        nextLevel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(139, 69, 19));
        setOpaque(false);

        upgradeName.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        upgradeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upgradeName.setText("Upgrade");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        description.setBackground(new java.awt.Color(139, 69, 19));
        description.setColumns(20);
        description.setEditable(false);
        description.setFont(new java.awt.Font("Bangla MN", 0, 12)); // NOI18N
        description.setLineWrap(true);
        description.setRows(3);
        description.setWrapStyleWord(true);
        description.setDragEnabled(false);
        description.setFocusable(false);
        description.setOpaque(false);
        description.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(description);

        jButton1.setText("Upgrade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Current Level:");

        jLabel3.setText("Level Up Cost:");

        currentLevel.setText("jLabel4");

        nextLevel.setText("jLabel5");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(upgradeName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(18, 18, 18))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(currentLevel)
                                    .add(nextLevel)))
                            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(upgradeName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(currentLevel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(nextLevel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButton1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentLevel;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nextLevel;
    private javax.swing.JLabel upgradeName;
    // End of variables declaration//GEN-END:variables
}
